repository:
  name: medapp-backend
  private: false
  default_branch: developer
  has_issues: true
  has_projects: false
  has_wiki: false

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true

  - name: staging
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1

  - name: developer
    protection: null
